version: '3'
services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
          - 80:80
          - 443:443
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./default-ssl.conf:/etc/nginx/conf.d/default.conf
          - ./fullchain.pem:/etc/letsencrypt/live/predex.duckdns.org/fullchain.pem
          - ./privkey.pem:/etc/letsencrypt/live/predex.duckdns.org/privkey.pem
          - ./options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
          - ./ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
